# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish1
      run: dotnet publish Demo.Auth.Servicio/Demo.Auth.Servicio.csproj -c Release1 -o release1
    - name: Upload a Build Artifact 1
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: DeployService1 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/Demo.Auth/Demo.Auth/release1/
    - name: Publish2
      run: dotnet publish Demo.Auth.Servicio2/Demo.Auth.Servicio2.csproj -c Release2 -o release2
    - name: Upload a Build Artifact 2
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: DeployService2 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/Demo.Auth/Demo.Auth/release2/
    - name: SmarterASP.NET Web Deploy
      # You may pin to the exact commit or the version.
      # uses: jahbenjah/SmarterASP.NET-web-deploy@845c19cd4b003b854908a1008b34fe97e98a56b1
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
      with:
        # IIS website name
        website-name: https://win5022.site4now.net:8172
        # IIS server computer name
        server-computer-name: mcobos-001-site11
        # IIS server username
        server-username: mcobos-001
        # IIS server password
        server-password: wiypYkwCva4LhO
          
    
